# Generated by Django 3.0.3 on 2020-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('quote', models.CharField(max_length=250)),
                ('context', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
