# Generated by Django 3.0.3 on 2020-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200512_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updaye_date',
        ),
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
