# Generated by Django 3.0.3 on 2020-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joboffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=120)),
                ('job_description', models.TextField(max_length=250)),
                ('salary', models.FloatField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
