# Generated by Django 3.0.3 on 2020-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200514_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_description',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_title',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
